config/routes.rb
Rails.application.routes.draw do


  get 'users/login' => 'sessions#new', as: :login
  post 'users/login' => 'sessions#create'
  delete 'users/logout' => "sessions#destroy", as: :logout


  root 'songs#index'


  get 'users' => 'users#index', as: :users
  get 'users/new' => 'users#new', as: :new_user
  post 'users' => 'users#create'
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy', as: :destroy_user
  get 'users/:id' => 'users#show', as: :user


  get 'songs' => 'songs#index', as: :songs
  get 'songs/:song_id' => 'songs#view', as: :view_song


  get 'about' => 'songs#about', as: :about
  get 'library' => 'songs#library', as: :library


  get 'users/:user_id/new' => 'songs#new', as: :user_songs
  post 'users/:user_id/new' => 'songs#create'
  get 'users/:user_id/:song_id/edit' => 'songs#edit', as: :user_song
  patch 'users/:user_id/:song_id/edit' => 'songs#update'
  delete 'users/:user_id/:song_id' => 'songs#destroy', as: :destroy_song
  get 'users/:user_id/:song_id' => 'songs#show', as: :song


  get 'songs/:song_id/comments' => 'comments#index'
  get 'songs/:song_id/comments/new' => 'comments#new'
  post 'songs/:song_id' => 'comments#create', as: :song_comments
  get 'songs/:song_id/comments/:id/edit' => 'comments#edit'
  get 'songs/:song_id/comments/:id' => 'comments#show'
  patch 'songs/:song_id/comments/:id' => 'comments#update'
  delete 'songs/:song_id/comments/:id' => 'comments#destroy', as: :destroy_comment

  # get 'songs/:song_id/like_song' => 'songs#upvote', as: 'upvote'
  patch 'songs/:song_id/like' => 'songs#upvote', as: :like_song
  # patch 'songs/:song_id/dislike' => 'songs#downvote', as: :dislike_song


end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :title, presence: true
	validates :artist, presence: true
	validates :year, presence: true

	acts_as_votable

	

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :test, presence: true

	has_many :songs, dependent: :destroy
	has_many :comments, dependent: :destroy

	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" } 
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@user = User.find( current_user.id )
		@comment = current_user.comments.new
	end

	def create
		@song = Song.find( params[:song_id] )
		@user = User.find( current_user.id )
		@comment = Comment.new( comment_params )

		if @comment.save
			redirect_to view_song_path(@song)
		else
			render :new
		end
	end

	def destroy
		@song = Song.find( params[:song_id] )
		@comment = Comment.find( params[:id] ) 
  		@comment.destroy
  		redirect_to view_song_path(@song)
	end

private

	def comment_params
		params.require( :comment ).permit( :body, :song_id, :name, :email, :user_id )
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email( params[:email] )
		if user && user.authenticate( params[:password] )
			session[:user_id] = user.id
			redirect_to user_path( current_user.id ), notice: "logged in!"
		else
			flash.now.alert = "invalid login credentials"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to users_path, notice: "logged out!"
	end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

	before_action :set_song, only:[:show, :view, :edit, :update, :destroy]

	def index
		@songs = Song.all.order( 'year DESC, title ASC' )
	end

	def about
	end

	def library
		@songs = Song.all.order( 'year DESC, title ASC' )
	end

	def show
		@youtube_id = @song.link.split("=").last
	end

	def view
		@youtube_id = @song.link.split("=").last
		@user_id = User.find( @song.user_id )
		@voter_id = @song.votes_for.voters
		@random = Song.all.order('RANDOM()').first
		@comment = Comment.new
	end

	def upvote 
		@song = Song.find( params[:song_id] )
		@song.upvote_by current_user
		redirect_to :back
	end

	def new
		@user = User.find( params[:user_id] )
		@song = @user.songs.new
	end

	def create
		@user = User.find( params[:user_id] )
		@song = @user.songs.new( song_params )
		if @song.save
			redirect_to view_song_path(@song.id)
		else
			render :new
		end
	end

	def edit
		@user = User.find( params[:user_id] )
	end

	def update
		@user = User.find( params[:user_id] )
		if @song.update_attributes( song_params )
			redirect_to view_song_path(@song.id)
		else
			render :edit
		end
	end

	def destroy
		@user = User.find( params[:user_id] )
		@song = @song.destroy
		redirect_to library_path
	end

private

	def song_params
		params.require( :song ).permit( :title, :artist, :year, :genre, :link, :user_id, :description, :lyrics, :embed )
	end

	def set_song
		@song = Song.find( params[:song_id] )
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only:[:show, :edit, :update, :destroy]

	def index
		@users = User.all.order( 'username ASC' )
	end

	def show
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new( user_params )
		if @user.save
		  redirect_to users_path
		else
		  render :new
		end
	end

	def edit
	end

	def update
	    if @user.update_attributes( user_params )
	      redirect_to user_path
	    else
	      render :edit
	    end
	end

	def destroy
		@user.destroy
		redirect_to users_path
	end

private

	def user_params
		params.require( :user ).permit( :first_name, :last_name, :username, :email, :password, :password_confirmation, :test, :discover, :gender, :date_of_birth, :favorite_song, :bio, :location, :image, :spotify_link, :soundcloud_link, :facebook_link, :youtube_link, :instagram_link, :twitter_link )
	end

	def set_user
		@user = User.find( params[:id] )
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<% if @song.comments.length > 0 %>
	<% @song.comments.each do |comment| %>
		<section class="comment">
			<p><%= comment.body %></p>
			<p><%= link_to '@'+comment.user.username, user_path(comment.user) %> ( <%= comment.created_at.strftime("%b %d, %Y") %> )</p>
			<% if @current_user == @user %>
				<p><%= link_to '[ Delete ]', destroy_comment_path( @song, comment), method: :delete %><p>
			<% end %>
		</section>
	<% end %>
<% else %>
	<section class="comment">
		<p>No comments have been posted yet.</p>
  	</section>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [ @user, song, @comment ] do |f| %>

	<h3><% f.label :name %></h3>
	<% f.text_field :name, class: 'text_field' %>

	<h3><% f.label :email %></h3>
	<% f.email_field :email, class: 'text_field' %>

	<h3><% f.label :body %></h3>
	<%= f.text_area :body, class: 'text_box' %>

	<% f.label :user_id %>
	<%= f.hidden_field :user_id, :value => current_user.id %>

	<% f.label :song_id %>
	<%= f.hidden_field :song_id, :value => song.id %>

	<%= f.submit class: 'nested_button' %>

<% end %>

app/views/comments/new.html.erb
<% render form %>

app/views/layouts/_footer.html.erb
<footer class="row">
	<div class="col-md-8 col-md-offset-2">
    <h4>EmpowerMIX</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</div>
</footer>

<footer class="row bottom">
	<div class="col-md-12">
    <p>© 2016 EmpowerMix</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="row">
	<div class="col-md-3 logo">
		<%= link_to 'EmpowerMIX', root_path %>
	</div>

  <nav class="col-md-9 nav-center">
    <ul>
      <!--<li><%= link_to 'MUSIC', library_path %></li>-->
      <li><%= link_to 'ABOUT', about_path %></li>
      <li><%= link_to 'CONTRIBUTORS', users_path %></li>

      <% if current_user %>
        <li><%= link_to '@'+ current_user.username, user_path(current_user.id) %></li>
        <li><%= link_to 'Log Out', logout_path, method: :delete, data: {confirm: 'Are you sure?'} %></li>
      <% else %>
        <li><button><%= link_to 'LOG IN', login_path %></button></li>
        <li><button><%= link_to 'SIGN UP', new_user_path %></button></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_message.html.erb
<% flash.each do |name, message| %>
	<section class="row blank">
		<div class="col-md-12">
			<h5><%= message %></h5>
		</div>
	</section>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="col-md-4">
	<section class="part">
	<p>HEART Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>

	<section class="part">
	<p>SHARE Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>

	<section class="part">
	<p>RANDOM FEATURED ARTIST Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>

	<section class="part">
	<p>AD Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>
</div> 

app/views/layouts/_song_sidebar.html.erb
<div class="col-md-4">
	<section class="part">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>

	<section class="part">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>

	<section class="part">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>
</div> 

app/views/layouts/_user_sidebar.html.erb
<div class="col-md-4">
	<section class="part">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>

	<section class="part">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>

	<section class="part">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</section>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmpowerMIX</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,500,600,700' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="container-fluid">
    
    <%= render 'layouts/header' %>
    
    <%= render 'layouts/message' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    
    <%#= console %>

  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [ @user, @song ] do |f| %>

	<section class='part'>
	<h3><%= f.label :title %></h3>
	<%= f.text_field :title, class: 'text_field' %>
	</section>

	<section class='part'>
	<h3><%= f.label :artist %></h3>
	<%= f.text_field :artist, class: 'text_field' %>
	</section>

	<section class='part'>
	<h3><%= f.label :year %></h3>
	<%= f.text_field :year, class: 'text_field' %>
	</section>

	<section class='part'>
	<h3><%= f.label :link, 'Youtube Link' %></h3>
	<%= f.url_field :link, class: 'text_field' %><br><br>

	<h3><%= f.label :embed, 'SoundCloud Embed' %></h3>
	<%= f.text_field :embed, class: 'text_field' %>
	</section>

	<section class='part'>
	<h3><%= f.label :genre %></h3>
	<%= f.select :genre, options_for_select([[ @song.genre, "" ], "Pop", "Hip-Hop", "Rock", "R&B", "Jazz", "Latin", "Metal", "Electronica", "Classical", "World", "Other" ]) %>
	</section>

	<section class='part'>
	<h3><%= f.label :description %></h3>
	<%= f.text_area :description, class: 'text_box description' %>
	</section>

	<section class='part'>
	<h3><%= f.label :lyrics %></h3>
	<%= f.text_area :lyrics, class: 'text_box lyrics' %>
	</section>

	<%= f.submit class: 'button' %>

<% end %>

app/views/songs/_like.html.erb
<h3><%= link_to like_song_path(@song), method: :patch do %> <3 <% end %>
	<% if @song.get_upvotes.size > 1 %>
		<%= @song.get_upvotes.size %> Likes	
	<% else %>
		<%= @song.get_upvotes.size %> Like
	<% end %>
</h3>

<% if @song.get_upvotes.size > 0 %>
	<hr><p>
	<% @song.votes_for.voters.each do |s| %>
		<%= link_to '@'+s.username, user_path(s.id) %>,
	<% end %>
	</p>
<% end %>

app/views/songs/edit.html.erb
<section class="row background">
	<div class="col-md-8">
		<section class='part'>
			<h1>Edit "<%= @song.title %>"</h1>
		</section>

		<%= render 'form' %>
	</div>
</section>

app/views/songs/library.html.erb
<section class="row blank">
  <div class="col-md-12">
    <h2>Music Library</h2>
    <% @songs.each do |song| %>
      <h3><%= song.year %> - 
      <%= link_to song.title, view_song_path(song) %> 
      by <%= song.artist %></h3>
    <% end %>
  </div>
</section>

app/views/songs/like_song.js.erb
$("post-<%=@song.id%>").html('<%=escape_javascript @song.get_upvotes.size %>')

app/views/songs/new.html.erb
<section class="row background">
	<div class="col-md-8">
		<section class='part'>
			<h1>New</h1>
		</section>

		<%= render 'form' %>
	</div>
</section>

app/views/songs/show.html.erb
<section class="row background">
	<div class="col-md-8">	
		<section class="part">
			<h1><%= @song.title %> (<%= @song.year %>) - <%= @song.artist %></h2>
			<p>Published on <%= @song.created_at.strftime("%b %d, %Y") %></p>
		</section>

		<section class="part">	
			<h3>Link:</h3>
			<p><a href="<%= @song.link %>"><%= @song.link %></a></p>
		</section>
		
		<section class="video">	
			<iframe width="560" height="315" src="//www.youtube.com/embed/<%= @youtube_id %>" frameborder="0" allowfullscreen></iframe>
		</section>

		<section class="part">	
			<h3>Description:</h3>
			<p class="text"><%= @song.description %></p>
		</section>

		<section class="part">			
			<h3>Lyrics:</h3>
			<p class="text"><%= @song.lyrics %></p>
		</section>

		<section class="part">	
			<h3>Genre:</h3>
			<p><%= @song.genre %></p>
		</section>

		<% if @current_user == @user %>
			<section class="part">	
				<%= link_to '[ Edit ]', user_song_path %> 
				<%= link_to '[ Delete ]', destroy_song_path, method: :delete %> 
				<%= link_to '[ Back to Profile ]', user_path( @song.user_id ) %>
			</section>
		<% else %>
			<section class="part">	 
				<%= link_to '[ Back to Profile ]', user_path( @song.user_id ) %>
			</section>
		<% end %>
	</div> 
</section>

app/views/songs/view.html.erb
<section class="row background">
	<div class="col-md-8">	

		<% if @song.link.nil? %>
		<% elsif @song.link.length > 0 %>
			<section class="video">
				<iframe width="100%" height="315" src="//www.youtube.com/embed/<%= @youtube_id %>?rel=0&amp;showinfo=0&autoplay=1" frameborder="0" allowfullscreen></iframe>
			</section>
		<% else %>
		<% end %>

		<% if @song.embed.nil? %>
		<% elsif @song.embed.length > 0 %>
			<section class="music">
				<%= @song.embed.html_safe %>
			</section>
		<% else %>
		<% end %>

		<section class="part">
			<h1><%= @song.title %> (<%= @song.year %>) - <%= @song.artist %></h1>
			<p>Published on <%= @song.created_at.strftime("%b %d, %Y") %> <%= link_to '@'+@user_id.username, user_path(@user_id) %></p>
			<p class="text"><%= @song.description %></p>
			<p><em><%= @song.genre %></em></p>
			<hr><h4>Share</h4>
			<%= social_share_button_tag( "Listening to "+ @song.artist + "'s " + @song.title + " on #EmpowerMIX", :url => "http://EmpowerMIX.com/", :image => "http://foo.bar/images/a.jpg", desc: "The summary of page", via: "EmpowerMIX" )%>
		</section>

		<% if @song.lyrics.nil? %>
		<% elsif @song.lyrics.length > 0 %>
			<section class="part">		
				<h4>Lyrics:</h4>
				<p class="text"><%= @song.lyrics %></p>
			</section>
		<% else %>
		<% end %>

		<%= render 'comments/comments' %>

		<section class="part"> 
			<% if current_user.nil? %>
				<h3><%= link_to 'log In', login_path %> or <%= link_to 'Sign Up', new_user_path %> to Leave a Comment</h3>
			<% else %>
				<h3>Leave a Comment:</h3>
				<%= render 'comments/form', :song => @song %>
			<% end %>
		</section>

		<div class="view_button"><%= link_to 'Back to Library', library_path %></div> 

		<%# raise current_user %>
		<% if current_user == @user_id %>
			<section class="part">
				<p>YouTube Link: <a href="<%= @song.link %>"><%= @song.link %></a></p>
				<p>Updated on <%= @user_id.updated_at.strftime("%b %d, %Y") %></p>	
				<%= link_to '[ Edit ]', user_song_path(@song.user_id, @song.id) %> 
				<%= link_to '[ Delete ]', destroy_song_path(@song.user_id, @song.id), method: :delete %>  
			</section>
		<% end %>

	</div> 







	<div class="col-md-4">
		<% if current_user.nil? %>
			<section class="part">
				<% if @song.get_upvotes.size > 1 || @song.get_upvotes.size == 0 %>
					<%= @song.get_upvotes.size %> Likes	
				<% else %>
					<%= @song.get_upvotes.size %> Like
				<% end %>

				<% if @song.get_upvotes.size > 0 %>
					<hr><p>
					<% @song.votes_for.voters.each do |s| %>
						<%= link_to '@'+s.username, user_path(s.id) %>,
					<% end %>
					</p>
				<% end %>
			</section>
		<% else %>

			<%= link_to like_song_path(@song), method: :patch do %>
				<div class="like"><span class="glyphicon glyphicon-heart"></span></div>
			<% end %> 

			
			<section class="part">					
				<% if @song.get_upvotes.size > 1 %>
					<%= @song.get_upvotes.size %> Likes	
				<% else %>
					<%= @song.get_upvotes.size %> Like
				<% end %>

				</h3>

				<% if @song.get_upvotes.size > 0 %>
					<hr><p>
					<% @song.votes_for.voters.each do |s| %>
						<%= link_to '@'+s.username, user_path(s.id) %>,
					<% end %>
					</p>
				<% end %>
			</section>
		<% end %>

		<div class="view_button"><%= link_to 'Next: '+ @random.title, view_song_path(@random) %></div> 

		<section class="part">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
		</section>

		<section class="part">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
		</section>
	</div> 
</section>

app/views/users/edit.html.erb
<section class="row background">
	<div class="col-md-8">
		<section class='part'>
			<h1>Edit <%= '@' + @user.username %></h1>
		</section>
		<%= render 'form' %>
	</div> 
	
	<%= render 'layouts/user_sidebar' %>
</section>

app/views/users/index.html.erb
<section class="row blank">
	<div class="col-md-10">
		<h1>Contributors</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</div>
</section>

<section class="row background">
	<div class="col-md-8">
		<% @users.each do |user| %>
			<section class="part">
			<h2><%= link_to  user.first_name + ' ' + user.last_name, user_path(user) %> <%= '@' + user.username %></h2>
			<h5>Favorite Song: <%= user.favorite_song %></h5>
			</section>
		<% end %>
		
		<% if @current_user != @user %>
			<section class="part">
				<%= link_to '[ Log In ]', new_user_path %>
				<%= link_to '[ Sign Up ]', new_user_path %>
			</section>
		<% end %>

	</div> 

	<%= render 'layouts/user_sidebar' %>
</section>

app/views/users/show.html.erb
<section class="row background">
	<div class="col-md-4">
		<section class="part">
			<% if @user.image.url == "/images/original/missing.png" %>
				<img src="/images/avatar.png">
			<% else %>
				<%= image_tag @user.image.url(:large) %>
			<% end %>
		</section>

		<% if @user.spotify_link.nil? %>
		<% elsif @user.spotify_link.length > 0 %>
			<a href="<%= @user.spotify_link %>" target="_blank">
			<div class="spotify">Spotify</a></div>
		<% else %>
		<% end %>

		<% if @user.soundcloud_link.nil? %>
		<% elsif @user.soundcloud_link.length > 0 %>
			<div class="soundcloud" ><a href="<%= @user.soundcloud_link %>" target="_blank">SoundCloud</a></div>
		<% else %>
		<% end %>

		<% if @user.facebook_link.nil? %>
		<% elsif @user.facebook_link.length > 0 %>		
			<div class="facebook"><a href="<%= @user.facebook_link %>" target="_blank">Facebook</a></div>
		<% else %>
		<% end %>

		<% if @user.youtube_link.nil? %>
		<% elsif @user.youtube_link.length > 0 %>	
			<div class="youtube"><a href="<%= @user.youtube_link %>" target="_blank">Youtube</a></div>
		<% else %>
		<% end %>

		<% if @user.instagram_link.nil? %>
		<% elsif @user.instagram_link.length > 0 %>	
			<div class="instagram"><a href="<%= @user.instagram_link %>" target="_blank">Instagram</a></div>
		<% else %>
		<% end %>

		<% if @user.twitter_link.nil? %>
		<% elsif @user.twitter_link.length > 0 %>		
			<div class="twitter"><a href="<%= @user.twitter_link %>" target="_blank">Twitter</a></div>
		<% else %>
		<% end %>

		<% if current_user == @user %>
			<hr>
			<div class="edit"><%= link_to 'Edit Profile', edit_user_path %></div>
			<div class="delete"><%= link_to 'Delete Account', destroy_user_path, method: :delete %></div>
		<% else %>
		<% end %>
	</div> 




	<div class="col-md-8">	
		<section class="part">
			<h1><%= @user.first_name %> <%= @user.last_name %></h1>
			<h4><%= '@' + @user.username %></h4>
			<p class= "text">Bio: <em><%= @user.bio %></em></p>
			<p>Favorite Song: <%= @user.favorite_song %></p>
			<p>Location: <%= @user.location %></p>
			<p>Member since: <%= @user.created_at.strftime("%Y") %></p>
		</section>

		<section class="part">
			<% if @user.songs.count == 1 %> 
				<h2><%= @user.songs.count %> Contribution</h2>
			<% elsif @user.songs.count > 1 %>
				<h2><%= @user.songs.count %> Contributions</h2>
			<% else %>
				<h3><%= @user.first_name %> hasn't made any contributions yet.</h3>
			<% end %>

			<ul>				
			<% @user.songs.order( 'created_at DESC, title ASC' ).each do |song| %>
				<li><h3><%= link_to song.title, view_song_path(song) %> by <%= song.artist %></h3>
				<p> <%= song.created_at.strftime("%b %d, %Y") %></p></li>
			<% end %>
			</ul>

			<% if current_user == @user %>	
				<%= link_to '[ Submit a New Song ]', user_songs_path(@user) %> 
			<% end %>
		</section>

		<div class="view_button"><%= link_to 'Back to Contributors', users_path %></div>
	</div>
</section>	